### ISSUE TITLE
Images should appear beside text in Usage section of the Design tab

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux-docs-tools#152]
In the Don't use when section of the error component docs, we have a couple images that are too big to show up beside the text and show up under. These images appeared beside the text in the old version of the docs at https://developer.blackbaud.com/skyux/components/error, and the files were copied directly from the `skyux2-docs` repo. But when we create the new version of the docs with `docs-tools` at https://developer.blackbaud.com/skyux-errors/docs/error, they no longer wrap correctly for some reason. I asked @Blackbaud-AlexKingman about this, and he said we should file an issue.

![image](https://user-images.githubusercontent.com/7850105/97005253-32bd7500-150c-11eb-8694-ddc4573688dc.png)

**Comment by Blackbaud-TrevorBurch** [comment]
This appears fixed now
