### ISSUE TITLE
Update H2 and H3 headers to conform to Stache header styles

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux-docs-tools#16]
Header styles are slightly different in the docs using the docs tools components. Need to tweak them to match the existing styles in Stache headers:

![image](https://user-images.githubusercontent.com/7850105/72904125-6ad52480-3cfc-11ea-8814-85f63b93d6bb.png)

**Comment by Blackbaud-SteveBrush** [comment]
According to @Blackbaud-ToddRoberts we'll also need to change the "Demo" heading to use the Stache H2 styles.
![](https://user-images.githubusercontent.com/15896944/72904248-9526e200-3cfc-11ea-8c30-ba0b3ce074ac.png)
