### ISSUE TITLE
Demo options popover displays cut off when only a reset button is shown

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-docs-tools#31]
When only a reset option is available for a component demo the top of the popover is cut off and the bottom border of the triggering button is cut off.

![image](https://user-images.githubusercontent.com/19909569/74565828-18280a80-4f40-11ea-9b23-a839c1c879b6.png)

**Comment by Blackbaud-AdamFunderburk** [comment]
First guess: in cases where a demo includes ONLY a "Reset" action and no other options, display the Reset button immediately to the right of the header.
![image](https://user-images.githubusercontent.com/15896944/76097907-7fad0500-5f96-11ea-9a27-a798d1fea63c.png)
