### ISSUE TITLE
Update table styles to allow for large images

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux-docs-tools#33]
Currently when trying to display wide images in the lefthand column of a table with the following HTML:
```        <table class="sky-docs-table">
          <tr>
            <td class="sky-docs-table-cell">
```
The images collapse to a narrow width that makes them unreadable: 
![image](https://user-images.githubusercontent.com/7850105/74770946-4ae14400-525b-11ea-9bc2-c7b4546f1b2e.png)

**Comment by Blackbaud-SteveBrush** [comment]
You should use the `sky-docs-thumbnail` component when implementing a general image. The `sky-docs-design-guideline-thumbnail` is used when you want a large thumbnail to appear to the right of a design guideline, in column format.
