### ISSUE TITLE
Anchor link service breaks on known type names when they're paired with their properties (Foo.Bar)

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux-docs-tools#63]
For the `messageStream` property in the pending progress indicator docs, the docs show an `a` tag for the `SkyProgressIndicatorMessageType` text even though there is no a tag in the JSDoc comments. See the docs PR at https://github.com/blackbaud/skyux-progress-indicator/pull/37.

**Comment by Blackbaud-AlexKingman** [comment]
I was able to replicate when I added apostrophes around an object with a `.` in it. For example, this renders fine:
```
  /**
   * Used in conjunction with SkyProgressIndicatorMessageType.GoTo
   ...
```
But this will result in showing the `<a>` tag:
```
  /**
   * Used in conjunction with `SkyProgressIndicatorMessageType.GoTo`
   ...
```
